# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20170809_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='posicion',
            field=models.IntegerField(default=-1),
        ),
    ]
